name: Slovian Engine
on:
  push:
    paths:
      - '**.json'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install --upgrade pip
      - name: Run Learning Script
        run: python app.py
      - name: Commit and Push
        run: |
          git config --global user.name 'SlovianBot'
          git config --global user.email 'bot@slovian.org'
          git add .
          git commit -m "Automated update" || exit 0
          git push
